"""
utils.py — Helper utilities, word extraction, VEDA AI insights & report helpers
"""

import re
import pandas as pd
from collections import Counter

EMOJI = {
    "POSITIVE": "😊",
    "NEUTRAL": "😐",
    "NEGATIVE": "😞"
}

SAMPLES = {
    "😊 Positive": "I absolutely loved this movie, the acting was fantastic!",
    "😞 Negative": "This was the worst service I have ever experienced.",
    "😐 Neutral": "The package arrived on Tuesday.",
    "⚖️ Mixed": "The food was great but the waiter was really rude."
}

STOPWORDS = set(
    "the a an and or but is are was were be been to of in on at for with this that it "
    "i you he she we they my your our their its as by from not no so very just have has had "
    "do does did will would can could".split()
)

POS_WORDS = set("loved fantastic great excellent amazing good wonderful best enjoy awesome super delighted happy love clear fast".split())
NEG_WORDS = set("worst rude terrible awful bad horrible waste poor broke disappointed hate fail broken standard issue slow crash".split())


def top_words(texts: list, n: int = 15) -> pd.DataFrame:
    """Extract top n most frequent non-stop words across texts."""
    words = []
    for t in texts:
        words += [
            w for w in re.findall(r"[a-zA-Z']+", str(t).lower())
            if w not in STOPWORDS and len(w) > 2
        ]
    if not words:
        return pd.DataFrame(columns=["Count"])
    counts = Counter(words).most_common(n)
    df = pd.DataFrame(counts, columns=["Word", "Count"]).set_index("Word")
    return df


def extract_keywords(text: str) -> dict:
    """Extract meaningful terms and split into positive and negative indicators."""
    words = [w.lower() for w in re.findall(r"[a-zA-Z']+", text) if len(w) > 2 and w not in STOPWORDS]
    pos_found = [w for w in set(words) if w in POS_WORDS]
    neg_found = [w for w in set(words) if w in NEG_WORDS]
    all_chips = list(set(words))[:10]
    return {
        "all": all_chips,
        "positive": pos_found,
        "negative": neg_found
    }


def generate_veda_insight(sentiment: str, confidence: float, emotion: str, text: str, model_name: str) -> str:
    """
    Generate deterministic AI insight summary based on model output & emotion.
    Clearly labeled as 'AI-generated insight'.
    """
    if sentiment == "POSITIVE":
        if confidence > 90:
            return f"VEDA detected a strongly positive tone with high model confidence ({confidence:.1f}%) using {model_name}. Key markers express enthusiasm ({emotion})."
        else:
            return f"VEDA identified a moderately positive overall sentiment ({confidence:.1f}%), aligned with {emotion} emotion traits."
    elif sentiment == "NEGATIVE":
        if confidence > 90:
            return f"VEDA detected a strongly critical or negative tone with high confidence ({confidence:.1f}%) via {model_name}, highlighting {emotion} triggers."
        else:
            return f"VEDA flagged negative sentiment nuances ({confidence:.1f}%) with primary emotion mapped to {emotion}."
    else:
        return f"VEDA classified the input as objective or neutral ({confidence:.1f}% confidence) with balanced phrasing and {emotion} tone."


def generate_analysis_report(df_results: pd.DataFrame, model_name: str) -> str:
    """Generate markdown summary for batch processing downloads."""
    total = len(df_results)
    if total == 0:
        return "# VEDA Batch Intelligence Report\nNo data analyzed."

    sentiment_counts = df_results["Predicted"].value_counts().to_dict() if "Predicted" in df_results.columns else {}
    avg_conf = df_results["Confidence (%)"].mean() if "Confidence (%)" in df_results.columns else 0.0

    report = f"""# 📊 VEDA — Voice, Emotion & Data Analytics Report
*Generated by VEDA Intelligence Platform*

---

### Executive Summary
- **Model Engine:** `{model_name}`
- **Total Records Analyzed:** `{total}`
- **Average Model Confidence:** `{avg_conf:.2f}%`

### Sentiment Breakdown
- **Positive:** `{sentiment_counts.get('POSITIVE', 0)}` ({(sentiment_counts.get('POSITIVE', 0)/total)*100:.1f}%)
- **Neutral:** `{sentiment_counts.get('NEUTRAL', 0)}` ({(sentiment_counts.get('NEUTRAL', 0)/total)*100:.1f}%)
- **Negative:** `{sentiment_counts.get('NEGATIVE', 0)}` ({(sentiment_counts.get('NEGATIVE', 0)/total)*100:.1f}%)

---

### Top Key Terms
"""
    if "Text" in df_results.columns:
        tw = top_words(df_results["Text"].tolist(), n=10)
        for word, row in tw.iterrows():
            report += f"- **{word}**: {row['Count']} occurrences\n"

    report += "\n---\n*Report generated automatically by VEDA Intelligence Engine.*"
    return report
